bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 0.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 2.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 5.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 7.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 10.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 12.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 15.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 17.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 20.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 22.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 25.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 27.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 30.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 32.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 35.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 37.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 40.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 42.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 45.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 47.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 50.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 52.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 55.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 57.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 60.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 62.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 65.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 67.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 70.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 72.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 75.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 77.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 80.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run.sh 82.5
