bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -85.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -82.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -80.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -77.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -75.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -72.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -70.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -67.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -65.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -62.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -60.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -57.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -55.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -52.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -50.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -47.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -45.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -42.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -40.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -37.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -35.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -32.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -30.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -27.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -25.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -22.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -20.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -17.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -15.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -12.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -10.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -7.5
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -5.0
bash /data/condor_builds/users/jasonfan/3ml_sensitivity_v42/flux/run_2.5.sh -2.5